// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/streaming.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamingServiceClient is the client API for StreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamingServiceClient interface {
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...grpc.CallOption) (StreamingService_ServerStreamClient, error)
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (StreamingService_ClientStreamClient, error)
	BiDirectionalStream(ctx context.Context, opts ...grpc.CallOption) (StreamingService_BiDirectionalStreamClient, error)
}

type streamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingServiceClient(cc grpc.ClientConnInterface) StreamingServiceClient {
	return &streamingServiceClient{cc}
}

func (c *streamingServiceClient) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...grpc.CallOption) (StreamingService_ServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamingService_ServiceDesc.Streams[0], "/streaming.StreamingService/ServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamingServiceServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamingService_ServerStreamClient interface {
	Recv() (*ServerStreamResponse, error)
	grpc.ClientStream
}

type streamingServiceServerStreamClient struct {
	grpc.ClientStream
}

func (x *streamingServiceServerStreamClient) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamingServiceClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (StreamingService_ClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamingService_ServiceDesc.Streams[1], "/streaming.StreamingService/ClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamingServiceClientStreamClient{stream}
	return x, nil
}

type StreamingService_ClientStreamClient interface {
	Send(*ClientStreamRequest) error
	CloseAndRecv() (*ClientStreamResponse, error)
	grpc.ClientStream
}

type streamingServiceClientStreamClient struct {
	grpc.ClientStream
}

func (x *streamingServiceClientStreamClient) Send(m *ClientStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamingServiceClientStreamClient) CloseAndRecv() (*ClientStreamResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ClientStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamingServiceClient) BiDirectionalStream(ctx context.Context, opts ...grpc.CallOption) (StreamingService_BiDirectionalStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamingService_ServiceDesc.Streams[2], "/streaming.StreamingService/BiDirectionalStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamingServiceBiDirectionalStreamClient{stream}
	return x, nil
}

type StreamingService_BiDirectionalStreamClient interface {
	Send(*BiDirectionalStreamRequest) error
	Recv() (*BiDirectionalStreamResponse, error)
	grpc.ClientStream
}

type streamingServiceBiDirectionalStreamClient struct {
	grpc.ClientStream
}

func (x *streamingServiceBiDirectionalStreamClient) Send(m *BiDirectionalStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamingServiceBiDirectionalStreamClient) Recv() (*BiDirectionalStreamResponse, error) {
	m := new(BiDirectionalStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamingServiceServer is the server API for StreamingService service.
// All implementations must embed UnimplementedStreamingServiceServer
// for forward compatibility
type StreamingServiceServer interface {
	ServerStream(*ServerStreamRequest, StreamingService_ServerStreamServer) error
	ClientStream(StreamingService_ClientStreamServer) error
	BiDirectionalStream(StreamingService_BiDirectionalStreamServer) error
	mustEmbedUnimplementedStreamingServiceServer()
}

// UnimplementedStreamingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStreamingServiceServer struct {
}

func (UnimplementedStreamingServiceServer) ServerStream(*ServerStreamRequest, StreamingService_ServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStream not implemented")
}
func (UnimplementedStreamingServiceServer) ClientStream(StreamingService_ClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStream not implemented")
}
func (UnimplementedStreamingServiceServer) BiDirectionalStream(StreamingService_BiDirectionalStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method BiDirectionalStream not implemented")
}
func (UnimplementedStreamingServiceServer) mustEmbedUnimplementedStreamingServiceServer() {}

// UnsafeStreamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingServiceServer will
// result in compilation errors.
type UnsafeStreamingServiceServer interface {
	mustEmbedUnimplementedStreamingServiceServer()
}

func RegisterStreamingServiceServer(s grpc.ServiceRegistrar, srv StreamingServiceServer) {
	s.RegisterService(&StreamingService_ServiceDesc, srv)
}

func _StreamingService_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamingServiceServer).ServerStream(m, &streamingServiceServerStreamServer{stream})
}

type StreamingService_ServerStreamServer interface {
	Send(*ServerStreamResponse) error
	grpc.ServerStream
}

type streamingServiceServerStreamServer struct {
	grpc.ServerStream
}

func (x *streamingServiceServerStreamServer) Send(m *ServerStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StreamingService_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingServiceServer).ClientStream(&streamingServiceClientStreamServer{stream})
}

type StreamingService_ClientStreamServer interface {
	SendAndClose(*ClientStreamResponse) error
	Recv() (*ClientStreamRequest, error)
	grpc.ServerStream
}

type streamingServiceClientStreamServer struct {
	grpc.ServerStream
}

func (x *streamingServiceClientStreamServer) SendAndClose(m *ClientStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamingServiceClientStreamServer) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StreamingService_BiDirectionalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingServiceServer).BiDirectionalStream(&streamingServiceBiDirectionalStreamServer{stream})
}

type StreamingService_BiDirectionalStreamServer interface {
	Send(*BiDirectionalStreamResponse) error
	Recv() (*BiDirectionalStreamRequest, error)
	grpc.ServerStream
}

type streamingServiceBiDirectionalStreamServer struct {
	grpc.ServerStream
}

func (x *streamingServiceBiDirectionalStreamServer) Send(m *BiDirectionalStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamingServiceBiDirectionalStreamServer) Recv() (*BiDirectionalStreamRequest, error) {
	m := new(BiDirectionalStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamingService_ServiceDesc is the grpc.ServiceDesc for StreamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.StreamingService",
	HandlerType: (*StreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStream",
			Handler:       _StreamingService_ServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStream",
			Handler:       _StreamingService_ClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BiDirectionalStream",
			Handler:       _StreamingService_BiDirectionalStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/streaming.proto",
}
